version: "3.8"

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    platform: linux/amd64
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=12345
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

  flask:
    container_name: hrflask
    image: hrflask
    build: ./app
    command: python API/app.py
    ports:
      - 5001:5000
    links:
      - mysql
    depends_on:
      - mysql
    volumes:
      - ./app:/app

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin:latest
    container_name: flask_phpmyadmin
    restart: unless-stopped
    ports:
      - "5010:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 12345